export const stocksMetadata = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    industry: "Consumer Electronics",
    ImageUrl: "https://financialmodelingprep.com/image-stock/AAPL.png",
    country: "United States",
    about:
      "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides digital content stores and streaming services; AppleCare support services; and iCloud, a cloud service, which stores music, photos, contacts, calendars, mail, documents, and others. In addition, the company offers various service, such as Apple Arcade, a game subscription service; Apple Card, a co-branded credit card; Apple News+, a subscription news and magazine service; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store, Mac App Store, and Watch App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    sector: "Technology",
    industry: "Software—Infrastructure",
    ImageUrl: "https://financialmodelingprep.com/image-stock/MSFT.png",
    country: "United States",
    about:
      "Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, and OneDrive; LinkedIn that includes Talent, Learning, Sales, and Marketing solutions, as well as premium subscriptions; and Dynamics 365, a set of cloud-based and on-premises business solutions for small and medium businesses, large organizations, and divisions of enterprises. Its Intelligent Cloud segment licenses SQL and Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also provides support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification to developers and IT professionals on various Microsoft products. Its More Personal Computing segment offers Windows OEM licensing and other non-volume licensing of the Windows operating system; Windows Commercial comprising volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also provides Microsoft Surface, PC accessories, and other intelligent devices; Gaming, including Xbox hardware, and Xbox software and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. It has a strategic collaboration with DXC Technology. The company was founded in 1975 and is headquartered in Redmond, Washington.",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    ImageUrl: "https://financialmodelingprep.com/image-stock/GOOGL.png",
    country: "United States",
    about:
      "Alphabet Inc. provides online advertising services in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It offers performance and brand advertising services. The company operates through Google and Other Bets segments. The Google segment offers products, such as Ads, Android, Chrome, Google Cloud, Google Maps, Google Play, Hardware, Search, and YouTube, as well as technical infrastructure. This segment also offers digital content, cloud services, hardware devices, and other miscellaneous products and services. The Other Bets segment includes businesses, including Access, Calico, CapitalG, GV, Verily, Waymo, and X, as well as Internet and television services. Alphabet Inc. was founded in 1998 and is headquartered in Mountain View, California.",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    ImageUrl: "https://financialmodelingprep.com/image-stock/AMZN.png",
    country: "United States",
    about:
      "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It sells merchandise and content purchased for resale from third-party sellers through physical and online stores. The company also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, and Echo and other devices; provides Kindle Direct Publishing, an online service that allows independent authors and publishers to make their books available in the Kindle Store; and develops and produces media content. In addition, it offers programs that enable sellers to sell their products on its websites, as well as its stores; and programs that allow authors, musicians, filmmakers, app developers, and others to publish and sell content. Further, the company provides compute, storage, database, and other AWS services, as well as fulfillment, advertising, publishing, and digital content subscriptions. Additionally, it offers Amazon Prime, a membership program, which provides free shipping of various items; access to streaming of movies and TV episodes; and other services. The company also operates in the food delivery business in Bengaluru, India. Amazon.com, Inc. has a strategic partnership with NXP Semiconductors N.V. The company was founded in 1994 and is headquartered in Seattle, Washington.",
  },
  {
    symbol: "FB",
    name: "Meta Platforms Inc.",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    ImageUrl: "https://financialmodelingprep.com/image-stock/FB.png",
    country: "United States",
    about:
      "Meta Platforms, Inc. develops products that enable people to connect and share with friends and family through mobile devices, personal computers, virtual reality headsets, wearables, and in-home devices worldwide. The company's products include Facebook that enables people to connect, share, discover, and communicate with each other on mobile devices and personal computers; Instagram, a community for sharing photos, videos, and private messages; Messenger, a messaging application for people to connect with friends, family, groups, and businesses across platforms and devices; and WhatsApp, a messaging application that is used by people and businesses to communicate in a private way. It also provides Facebook Reality Labs, an augmented and virtual reality product that help people feel connected, anytime, and anywhere. Meta Platforms, Inc. was founded in 2004 and is headquartered in Menlo Park, California.",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    ImageUrl: "https://financialmodelingprep.com/image-stock/TSLA.png",
    country: "United States",
    about:
      "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally. The company operates in two segments, Automotive, and Energy Generation and Storage. The Automotive segment offers electric vehicles, as well as sells automotive regulatory credits. It provides sedans and sport utility vehicles through direct and used vehicle sales, a network of Tesla Superchargers, and in-app upgrades; and purchase financing and leasing services. This segment is also involved in the provision of non-warranty after-sales vehicle services, sale of used vehicles, retail merchandise, and vehicle insurance, as well as sale of products through its subsidiaries to third party customers; services for electric vehicles through its company-owned service locations, and Tesla mobile service technicians; and vehicle limited warranties and extended service plans. The Energy Generation and Storage segment engages in the design, manufacture, installation, sale, and leasing of solar energy generation and energy storage products, and related services to residential, commercial, and industrial customers. It develops solar energy systems; develops, manufactures, installs, and maintains solar panels; and sells renewable energy to residential and commercial customers. This segment also provides vehicle insurance services, as well as renewable energy. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was founded in 2003 and is headquartered in Austin, Texas.",
  },
  {
    symbol: "BRK.A",
    name: "Berkshire Hathaway Inc.",
    sector: "Financial Services",
    industry: "Insurance—Diversified",
    ImageUrl: "https://financialmodelingprep.com/image-stock/BRK.A.png",
    country: "United States",
    about:
      "Berkshire Hathaway Inc. operates as a holding company. The company through its subsidiaries engages in insurance, freight rail transportation, and utility businesses. It provides property and casualty insurance and reinsurance, as well as life, accident, and health reinsurance; and operates railroad systems in North America. The company also generates, transmits, stores, and distributes electricity from natural gas, coal, wind, solar, hydro, nuclear, and geothermal sources; operates natural gas distribution and storage facilities, interstate pipelines, and compressor and meter stations; and holds interest in coal mining assets. In addition, it manufactures boxed chocolates and other confectionery products; specialty chemicals, metal cutting tools, and components for aerospace and power generation applications; flooring, insulation, roofing and engineered, building and engineered components, paints and coatings, and bricks and masonry products, as well as offers homebuilding and manufactured housing finance; recreational vehicles, apparel products, jewelry, and custom picture framing products; and alkaline batteries. Further, the company manufactures castings, forgings, fasteners/fastener systems, and aerostructures; and seamless pipes, fittings, downhole casing and tubing, and various mill forms. Additionally, it retails automobiles; furniture, bedding, and accessories; household appliances, electronics, and computers; jewelry, watches, crystal, china, stemware, flatware, gifts, and collectibles; kitchenware; and motorcycle apparel and equipment. The company distributes newspapers, news, and information; operates a residential real estate brokerage business; and invests in fixed-income and equity instruments. The company was incorporated in 1998 and is headquartered in Omaha, Nebraska.",
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    sector: "Financial Services",
    industry: "Credit Services",
    ImageUrl: "https://financialmodelingprep.com/image-stock/V.png",
    country: "United States",
    about:
      "Visa Inc. operates as a payments technology company worldwide. The company facilitates digital payments among consumers, merchants, financial institutions, businesses, strategic partners, and government entities. It operates VisaNet, a transaction processing network that enables authorization, clearing, and settlement of payment transactions. In addition, the company offers card products, as well as value-added services. It provides its services under the Visa, Visa Electron, Interlink, V PAY, and PLUS brands. Visa Inc. was founded in 1958 and is headquartered in San Francisco, California.",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    industry: "Drug Manufacturers—General",
    ImageUrl: "https://financialmodelingprep.com/image-stock/JNJ.png",
    country: "United States",
    about:
      "Johnson & Johnson researches and develops, manufactures, and sells various products in the health care field worldwide. It operates in three segments: Consumer Health, Pharmaceutical, and Medical Devices. The Consumer Health segment offers baby care products under the JOHNSON'S brand; oral care products under the LISTERINE brand; beauty products under the AVEENO, CLEAN & CLEAR, DR. CI:LABO, NEUTROGENA, and OGX brands; over-the-counter medicines, including acetaminophen products under the TYLENOL brand; cold, flu, and allergy products under the SUDAFED brand; allergy products under the BENADRYL brand; ibuprofen products under the MOTRIN IB brand; and acid reflux products under the PEPCID brand. This segment also provides women's health products, such as sanitary pads and tampons under the STAYFREE, CAREFREE, and o.b. brands; wound care products comprising adhesive bandages under the BAND-AID brand; and first aid products under the NEOSPORIN brand. The Pharmaceutical segment offers products in various therapeutic areas, including immunology, infectious diseases, neuroscience, oncology, pulmonary hypertension, and cardiovascular and metabolic diseases. The Medical Devices segment provides electrophysiology products to treat cardiovascular diseases; orthopaedic products in support of hip, knee, and shoulder procedures; advanced and general surgery, surgical oncology, and neurosurgery products; and disposable contact lenses. The company markets its products to general public, and retail outlets and distributors, as well as distributes directly to wholesalers, hospitals, and health care professionals for prescription use. Johnson & Johnson was founded in 1886 and is based in New Brunswick, New Jersey.",
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    ImageUrl: "https://financialmodelingprep.com/image-stock/WMT.png",
    country: "United States",
    about:
      "Walmart Inc. engages in the retail and wholesale operations in various formats worldwide. The company operates through three segments: Walmart U.S., Walmart International, and Sam's Club. It operates supercenters, supermarkets, hypermarkets, warehouse clubs, cash and carry stores, and discount stores; membership-only warehouse clubs; ecommerce websites, such as walmart.com, walmart.com.mx, walmart.ca, flipkart.com, and samsclub.com; and mobile commerce applications. The company offers grocery products, including meat, produce, natural and organics, deli and bakery, dairy, frozen foods, alcoholic and nonalcoholic beverages, floral and dry grocery, as well as consumables, such as health and beauty aids, baby products, household chemicals, paper goods, and pet supplies; and health and wellness products. It also provides electronics, cameras and supplies, photo processing services, wireless, movies, music, video games, and books; stationery, automotive, hardware and paint, sporting goods, outdoor living and horticulture, apparel, shoes, and jewelry; and home furnishings, housewares and small appliances, bedding, home decor, toys, fabrics, crafts, and seasonal merchandise; and fuel and financial services and related products, including money orders, prepaid cards, wire and money transfers, check cashing, and bill payment. In addition, the company offers brand name merchandise, including hardgoods, softgoods, and selected private-label items, such as Member's Mark. It operates approximately 10,500 stores and various e-commerce websites under the 48 banners in 24 countries. The company was founded in 1945 and is based in Bentonville, Arkansas.",
  },
];

export const bestKnownStockSymbols: string[] = [
  "AAPL",
  "MSFT",
  "GOOGL",
  // "AMZN",
  //   "FB",
  //   "TSLA",
  //   "BRK.A",
  //   "BRK.B",
  //   "V",
  //   "JNJ",
  //   "WMT",
  //   "JPM",
  //   "MA",
  //   "PG",
  //   "UNH",
  //   "NVDA",
  //   "HD",
  //   "DIS",
  //   "PYPL",
  //   "VZ",
  //   "ADBE",
  //   "NFLX",
  //   "INTC",
  //   "CMCSA",
  //   "KO",
  //   "PEP",
  //   "CSCO",
  //   "MRK",
  //   "PFE",
  //   "ABT",
  //   "T",
  //   "XOM",
  //   "CVX",
  //   "NKE",
  //   "LLY",
  //   "MCD",
  //   "MDT",
  //   "WFC",
  //   "BMY",
  //   "COST",
  //   "AMGN",
  //   "HON",
  //   "BA",
  //   "IBM",
  //   "TXN",
  //   "MMM",
  //   "UNP",
  //   "CAT",
  //   "GS",
  //   "LMT",
  //   "GE",
  //   "QCOM",
  //   "ORCL",
  //   "UPS",
  //   "MS",
  //   "BLK",
  //   "AXP",
  //   "SPGI",
  //   "NEE",
  //   "RTX",
  //   "SCHW",
  //   "TMO",
  //   "LOW",
  //   "INTU",
  //   "PLD",
  //   "ANTM",
  //   "DHR",
  //   "SBUX",
  //   "AMT",
  //   "MO",
  //   "CVS",
  //   "CI",
  //   "MDLZ",
  //   "ISRG",
  //   "BKNG",
  //   "SYK",
  //   "ZTS",
  //   "ADP",
  //   "CB",
  //   "GILD",
  //   "DUK",
  //   "SO",
  //   "MMC",
  //   "PNC",
  //   "USB",
  //   "CCI",
  //   "BDX",
  //   "TGT",
  //   "CME",
  //   "ICE",
  //   "NSC",
  //   "ITW",
  //   "APD",
  //   "CL",
  //   "ECL",
  //   "SHW",
  //   "FIS",
  //   "FISV",
  //   "EW",
  //   "AON",
  //   "MET",
  //   "AIG",
  //   "PRU",
  //   "TRV",
  //   "ALL",
  //   "HUM",
  //   "ANTM",
  //   "CNC",
  //   "CI",
  //   "UNH",
  //   "HCA",
  //   "DHR",
  //   "TMO",
  //   "BDX",
  //   "ISRG",
  //   "SYK",
  //   "ZTS",
  //   "ABT",
  //   "MDT",
  //   "BAX",
  //   "BSX",
  //   "EW",
  //   "HOLX",
  //   "IDXX",
  //   "ILMN",
  //   "IQV",
  //   "LH",
  //   "MCK",
  //   "STE",
  //   "TFX",
  //   "WAT",
  //   "XRAY",
  //   "ZBH",
  //   "ALGN",
  //   "BMY",
  //   "GILD",
  //   "MRK",
  //   "PFE",
  //   "LLY",
  //   "ABBV",
  //   "AMGN",
  //   "REGN",
  //   "VRTX",
  //   "BIIB",
  //   "INCY",
  //   "ALXN",
  //   "BMRN",
  //   "NBIX",
  //   "SAGE",
  //   "SRPT",
  //   "TSRO",
  //   "XLRN",
  //   "ACAD",
  //   "ALNY",
  //   "AMRN",
  //   "ARNA",
  //   "BPMC",
  //   "CARA",
  //   "CLVS",
  //   "CRSP",
  //   "EDIT",
  //   "FGEN",
  //   "GBT",
  //   "IONS",
  //   "KITE",
  //   "LGND",
  //   "MRTX",
  //   "NKTR",
  //   "NVCR",
  //   "PTCT",
  //   "RARE",
  //   "RGEN",
  //   "SAGE",
  //   "SRPT",
  //   "STML",
  //   "TGTX",
  //   "UTHR",
  //   "VYGR",
  //   "XLRN",
  //   "ZGNX",
];
